### ISSUE TITLE
Unknown Error. Please contact crispector package author

### ISSUE THREAD

**Issue by huoww07** [YakhiniGroup/crispector#3]
* crispector version: docker
* Python version: 3.7
* Operating System: ubuntu 18.04

### Description

I ran the program using docker image and encountered unknown error.

### What I Did

```
docker run -v ${PWD}:/DATA -w /DATA crispector_image crispector -t_r1 R1_001.fastq -t_r2 R2_001.fastq -m_r1 mock_R1_001.fastq -m_r2 mock_R2_001.fastq -c config.csv -o ./S16-1
```

See below for the crispector_main.log output
```
2021-10-21 01:17:42,494 WARNING	 Site A123 has highly unbalanced number of reads: Treatment - 9,426, Mock - 2,725.
2021-10-21 01:36:54,314 INFO	 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/crispector/crispector_main.py", line 155, in run
    site, site_output)
  File "/usr/local/lib/python3.7/site-packages/crispector/report/visualization_and_output.py", line 72, in create_site_output
    plot_edited_reads_to_table(mod_table, cut_site, output, html_d, base_path)
  File "/usr/local/lib/python3.7/site-packages/crispector/report/visualization_and_output.py", line 592, in plot_edited_reads_to_table
    colors[row_idx] = np.array(color_edit_background(read_w_ins, read_w_del) + ['lightgrey', 'lightgrey', 'black'])
ValueError: could not broadcast input array from shape (41) into shape (43)

2021-10-21 01:36:54,315 ERROR	 Unknown Error. Please contact crispector package author

```

**Comment by iamit87** [comment]
Hi, 
Can you please upload the input files? Or share them via google drive?

**Comment by iamit87** [comment]
Please reopen the issue once you supply instructions to reproduce.
